# Generated by Django 3.2.16 on 2023-02-01 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20230124_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
